-- ============================================================
--  BotQuest_Data.lua
--  Registro de misiones por rango de nivel
--  Recompensas: oro (en cobre) + item_id aleatorio del pool o Honor (si es PvP)
-- ============================================================

BotQuestData = {}

-- Duraciones en segundos (el timer del servidor respeta estos valores)
BotQuestData.DURATIONS = {
    SHORT  = 300,   --  5 min
    MEDIUM = 600,   -- 10 min
    LONG   = 1200,  -- 20 min
    EPIC   = 2400,  -- 40 min
}

-- Dificultad visual
BotQuestData.DIFFICULTY = {
    EASY    = { label = "Fácil",    color = "ff44ff44" },
    NORMAL  = { label = "Normal",   color = "ffffffff" },
    HARD    = { label = "Difícil",  color = "ffff8800" },
    ELITE   = { label = "Élite",    color = "ffff2222" },
}

-- ============================================================
--  POOL DE ITEMS POR RANGO  (item IDs de Vanilla/TBC/WotLK)
--  Se elige 1 al azar en el servidor Eluna
-- ============================================================
BotQuestData.ITEM_POOLS = {
    [1]  = { 6256, 6257, 6218, 4604, 4536 },        -- Lvl 1-10  (bolsas pequeñas, polvos, telas)
    [2]  = { 2840, 2842, 4234, 4236, 7067 },        -- Lvl 11-20
    [3]  = { 4338, 4340, 7286, 7287, 9210 },        -- Lvl 21-30
    [4]  = { 9213, 9214, 10561, 10562, 11176 },     -- Lvl 31-40
    [5]  = { 12065, 12066, 14047, 14048, 15419 },   -- Lvl 41-50
    [6]  = { 15420, 16057, 16058, 17111, 18632 },   -- Lvl 51-60
    [7]  = { 22682, 22683, 23736, 24114, 25521 },   -- Lvl 61-70
    [8]  = { 33463, 33464, 34721, 36234, 37060 },   -- Lvl 71-80
}

-- Helper: devuelve el índice de pool para un nivel dado
function BotQuestData:GetPoolIndex(level)
    if     level <= 10 then return 1
    elseif level <= 20 then return 2
    elseif level <= 30 then return 3
    elseif level <= 40 then return 4
    elseif level <= 50 then return 5
    elseif level <= 60 then return 6
    elseif level <= 70 then return 7
    else                    return 8
    end
end

-- ============================================================
--  MISIONES
--  Campos extra para PvP:
--    isPvP       -> true si es una misión orientada a JcJ (evita dar items del pool estándar)
--    honorPoints -> Puntos de honor que el script de Eluna debería otorgar
-- ============================================================
BotQuestData.QUESTS = {

    -- ─── NIVEL 1-10 ─────────────────────────────────────────
    {
        id         = "q_patrulla_aldea",
        name       = "Patrulla de la Aldea",
        desc       = "Los aldeanos necesitan protección. Envía tus bots a vigilar el perímetro durante la noche.",
        minLevel   = 1,
        maxLevel   = 10,
        difficulty = "EASY",
        duration   = BotQuestData.DURATIONS.SHORT,
        goldMin    = 50,
        goldMax    = 200,
        icon       = "Interface\\Icons\\Ability_Warrior_Charge",
    },
    {
        id         = "q_caza_menor",
        name       = "Caza Menor",
        desc       = "Las bestias del bosque se acercan demasiado. Despeja la zona.",
        minLevel   = 1,
        maxLevel   = 10,
        difficulty = "EASY",
        duration   = BotQuestData.DURATIONS.SHORT,
        goldMin    = 80,
        goldMax    = 250,
        icon       = "Interface\\Icons\\Ability_Hunter_BeastTraining",
    },
    {
        id         = "q_suministros_perdidos",
        name       = "Suministros Perdidos",
        desc       = "Un carro de carga fue asaltado cerca. Recupera las cajas antes que los carroñeros.",
        minLevel   = 3,
        maxLevel   = 10,
        difficulty = "EASY",
        duration   = BotQuestData.DURATIONS.SHORT,
        goldMin    = 60,
        goldMax    = 220,
        icon       = "Interface\\Icons\\inv_misc_enggizmos_17",
    },
    {
        id         = "q_plaga_jabalies",
        name       = "Plaga de Jabalíes",
        desc       = "Los jabalíes están destrozando los cultivos locales. Reduce su número.",
        minLevel   = 2,
        maxLevel   = 10,
        difficulty = "EASY",
        duration   = BotQuestData.DURATIONS.SHORT,
        goldMin    = 70,
        goldMax    = 240,
        icon       = "Interface\\Icons\\Ability_Tracking",
    },
    {
        id         = "q_escaramuza_practica",
        name       = "Escaramuza de Práctica",
        desc       = "Entrena a tus bots en un entorno controlado de combate contra la facción contraria.",
        minLevel   = 5,
        maxLevel   = 10,
        difficulty = "NORMAL",
        duration   = BotQuestData.DURATIONS.MEDIUM,
        goldMin    = 100,
        goldMax    = 300,
        icon       = "Interface\\Icons\\Ability_DualWield",
        isPvP      = true,
        honorPoints= 50,
    },
    {
        id         = "q_amenaza_centauro",
        name       = "Amenaza Centauro",
        desc       = "Exploradores reportan movimientos hostiles en las fronteras. Dispersa sus campamentos.",
        minLevel   = 6,
        maxLevel   = 10,
        difficulty = "NORMAL",
        duration   = BotQuestData.DURATIONS.MEDIUM,
        goldMin    = 120,
        goldMax    = 350,
        icon       = "Interface\\Icons\\INV_Spear_02",
    },
    {
        id         = "q_limpieza_minas",
        name       = "Limpieza de las Minas",
        desc       = "Los kóbolds o troggs han tomado los túneles inferiores. Despéjalos para los mineros.",
        minLevel   = 7,
        maxLevel   = 10,
        difficulty = "NORMAL",
        duration   = BotQuestData.DURATIONS.MEDIUM,
        goldMin    = 150,
        goldMax    = 400,
        icon       = "Interface\\Icons\\spell_shadow_summonimp",
    },
    {
        id         = "q_desafio_recluta",
        name       = "El Desafío del Recluta",
        desc       = "Muestra el temple de tu equipo desafiando a los campeones locales en un duelo de honor.",
        minLevel   = 8,
        maxLevel   = 10,
        difficulty = "HARD",
        duration   = BotQuestData.DURATIONS.LONG,
        goldMin    = 200,
        goldMax    = 500,
        icon       = "Interface\\Icons\\INV_Shield_05",
        isPvP      = true,
        honorPoints= 80,
    },

    -- ─── NIVEL 11-20 ─────────────────────────────────────────
    {
        id         = "q_escolta_mercader",
        name       = "Escolta del Mercader",
        desc       = "Un mercader necesita llegar sano y salvo a la ciudad. Que tus bots lo acompañen.",
        minLevel   = 11,
        maxLevel   = 20,
        difficulty = "NORMAL",
        duration   = BotQuestData.DURATIONS.MEDIUM,
        goldMin    = 300,
        goldMax    = 800,
        icon       = "Interface\\Icons\\INV_Misc_Bag_10",
    },
    {
        id         = "q_expurgar_cueva",
        name       = "Expurgar la Cueva",
        desc       = "Una cueva cercana está infestada de muertos vivientes. Limpia el nido.",
        minLevel   = 15,
        maxLevel   = 20,
        difficulty = "NORMAL",
        duration   = BotQuestData.DURATIONS.MEDIUM,
        goldMin    = 500,
        goldMax    = 1200,
        icon       = "Interface\\Icons\\spell_shadow_auraofdarkness",
    },
    {
        id         = "q_garganta_grito_guerra_baja",
        name       = "Frente en Grito de Guerra",
        desc       = "La batalla por los recursos forestales ha comenzado. Captura la bandera enemiga.",
        minLevel   = 11,
        maxLevel   = 20,
        difficulty = "HARD",
        duration   = BotQuestData.DURATIONS.LONG,
        goldMin    = 600,
        goldMax    = 1500,
        icon       = "Interface\\Icons\\Achievement_BG_WinWSG",
        isPvP      = true,
        honorPoints= 150,
    },
    {
        id         = "q_bandidos_caminos",
        name       = "Bandidos de los Caminos",
        desc       = "Una banda de forajidos está cobrando peajes ilegales en las rutas principales. Elimínalos.",
        minLevel   = 12,
        maxLevel   = 20,
        difficulty = "EASY",
        duration   = BotQuestData.DURATIONS.SHORT,
        goldMin    = 400,
        goldMax    = 900,
        icon       = "Interface\\Icons\\INV_Misc_Bone_HumanSkull_01",
    },
    {
        id         = "q_sabotaje_almanegra",
        name       = "Sabotaje Almanegra",
        desc       = "Infíltrate en los muelles de los piratas y quema sus planos de navegación.",
        minLevel   = 14,
        maxLevel   = 20,
        difficulty = "NORMAL",
        duration   = BotQuestData.DURATIONS.MEDIUM,
        goldMin    = 550,
        goldMax    = 1300,
        icon       = "Interface\\Icons\\Spell_Fire_Fire",
    },
    {
        id         = "q_fauna_corrupta",
        name       = "Fauna Corrupta",
        desc       = "Animales salvajes afectados por magia residual atacan a los viajeros. Ponles fin.",
        minLevel   = 13,
        maxLevel   = 20,
        difficulty = "EASY",
        duration   = BotQuestData.DURATIONS.SHORT,
        goldMin    = 450,
        goldMax    = 1000,
        icon       = "Interface\\Icons\\Spell_Nature_HealingWay",
    },
    {
        id         = "q_defensa_encrucijada",
        name       = "Defensa de la Encrucijada",
        desc       = "Repele las oleadas de atacantes que intentan asediar nuestro puesto de avanzada.",
        minLevel   = 16,
        maxLevel   = 20,
        difficulty = "HARD",
        duration   = BotQuestData.DURATIONS.LONG,
        goldMin    = 700,
        goldMax    = 1600,
        icon       = "Interface\\Icons\\Ability_Warrior_DefensiveStance",
    },
    {
        id         = "q_control_recursos_baja",
        name       = "Disputa de Suministros JcJ",
        desc       = "Intercepta un cargamento de suministros que la facción rival intenta reclamar.",
        minLevel   = 18,
        maxLevel   = 20,
        difficulty = "HARD",
        duration   = BotQuestData.DURATIONS.LONG,
        goldMin    = 800,
        goldMax    = 1800,
        icon       = "Interface\\Icons\\INV_BannerPVP_01",
        isPvP      = true,
        honorPoints= 200,
    },

    -- ─── ÉLITE 15-20 ─────────────────────────────────────────
    {
        id         = "q_elite_mina_garras",
        name       = "[ÉLITE] La Mina Infestada de Garras",
        desc       = "Una antigua mina al norte ha sido tomada por arañas carroñeras y sus reinas. Los colonos no se atreven a acercarse. Infiltra un equipo y extermina a la matriarca antes de que la infestación se extienda.",
        minLevel   = 15,
        maxLevel   = 20,
        difficulty = "ELITE",
        duration   = 900,
        goldMin    = 8000,
        goldMax    = 18000,
        icon       = "Interface\\Icons\\Ability_Rogue_Ambush",
    },
    {
        id         = "q_elite_muertos_errantes",
        name       = "[ÉLITE] Patrulla de los Muertos Errantes",
        desc       = "Desde el cementerio olvidado al este del poblado emergen no-muertos cada noche atacando las granjas cercanas. Elimina al nigromante que los levanta antes del próximo amanecer.",
        minLevel   = 15,
        maxLevel   = 20,
        difficulty = "ELITE",
        duration   = 1200,
        goldMin    = 10000,
        goldMax    = 22000,
        icon       = "Interface\\Icons\\Spell_Shadow_RaiseDead",
    },

    -- ─── NIVEL 21-30 ─────────────────────────────────────────
    {
        id         = "q_ruinas_antiguas",
        name       = "Ruinas Antiguas",
        desc       = "Explora las ruinas y recupera los artefactos antes de que caigan en malas manos.",
        minLevel   = 21,
        maxLevel   = 30,
        difficulty = "NORMAL",
        duration   = BotQuestData.DURATIONS.MEDIUM,
        goldMin    = 1000,
        goldMax    = 2500,
        icon       = "Interface\\Icons\\INV_Misc_Rune_01",
    },
    {
        id         = "q_incursion_campamento",
        name       = "Incursión al Campamento",
        desc       = "Un campamento enemigo amenaza la región. Asalto rápido y retirada.",
        minLevel   = 25,
        maxLevel   = 30,
        difficulty = "HARD",
        duration   = BotQuestData.DURATIONS.LONG,
        goldMin    = 2000,
        goldMax    = 4000,
        icon       = "Interface\\Icons\\Ability_Warrior_OffensiveStance",
    },
    {
        id         = "q_cuenca_arathi_baja",
        name       = "Batalla por la Cuenca",
        desc       = "Envía tus bots a capturar y defender las cinco bases clave de recursos.",
        minLevel   = 21,
        maxLevel   = 30,
        difficulty = "HARD",
        duration   = BotQuestData.DURATIONS.LONG,
        goldMin    = 2200,
        goldMax    = 4500,
        icon       = "Interface\\Icons\\Achievement_BG_WinAB",
        isPvP      = true,
        honorPoints= 300,
    },
    {
        id         = "q_caza_golem",
        name       = "Golems Descontrolados",
        desc       = "Golems de piedra antiguos han despertado y destruyen los caminos arqueológicos.",
        minLevel   = 22,
        maxLevel   = 30,
        difficulty = "NORMAL",
        duration   = BotQuestData.DURATIONS.MEDIUM,
        goldMin    = 1200,
        goldMax    = 2800,
        icon       = "Interface\\Icons\\INV_Stone_04",
    },
    {
        id         = "q_escaramuza_caminos",
        name       = "Conflictos Territoriales",
        desc       = "Las tensiones en las zonas en disputa aumentan. Da caza a los soldados de la otra facción.",
        minLevel   = 24,
        maxLevel   = 30,
        difficulty = "NORMAL",
        duration   = BotQuestData.DURATIONS.MEDIUM,
        goldMin    = 1500,
        goldMax    = 3200,
        icon       = "Interface\\Icons\\Ability_Gouge",
        isPvP      = true,
        honorPoints= 250,
    },
    {
        id         = "q_amenaza_grimpato",
        name       = "La Tribu Grimpato",
        desc       = "Los harrier y geománticos de esta tribu hostil están organizando una emboscada masiva.",
        minLevel   = 26,
        maxLevel   = 30,
        difficulty = "NORMAL",
        duration   = BotQuestData.DURATIONS.MEDIUM,
        goldMin    = 1800,
        goldMax    = 3800,
        icon       = "Interface\\Icons\\INV_Misc_Foot_Centaur",
    },
    {
        id         = "q_misterio_argenteo",
        name       = "El Secreto de la Arboleda",
        desc       = "Ayuda a los investigadores a purificar un pozo lunar infectado de siles.",
        minLevel   = 27,
        maxLevel   = 30,
        difficulty = "EASY",
        duration   = BotQuestData.DURATIONS.SHORT,
        goldMin    = 1100,
        goldMax    = 2600,
        icon       = "Interface\\Icons\\Spell_Nature_Lightning",
    },
    {
        id         = "q_asesinato_lider",
        name       = "Objetivo: El Comandante",
        desc       = "Asalta el búnker fortificado de la facción rival y descabeza su línea de mando regional.",
        minLevel   = 29,
        maxLevel   = 30,
        difficulty = "ELITE",
        duration   = BotQuestData.DURATIONS.EPIC,
        goldMin    = 3000,
        goldMax    = 6000,
        icon       = "Interface\\Icons\\achievement_boss_saurfang",
        isPvP      = true,
        honorPoints= 400,
    },

    -- ─── ÉLITE 22-28 ─────────────────────────────────────────
    {
        id         = "q_elite_senor_pantano",
        name       = "[ÉLITE] El Señor del Pantano",
        desc       = "Una criatura colosal domina los pantanos del sur hundiendo las barcazas de suministros. Los mercaderes ofrecen una recompensa generosa por su cabeza. El terreno dificulta el combate.",
        minLevel   = 22,
        maxLevel   = 28,
        difficulty = "ELITE",
        duration   = 1200,
        goldMin    = 18000,
        goldMax    = 35000,
        icon       = "Interface\\Icons\\Ability_Hunter_SwiftStrike",
    },
    {
        id         = "q_elite_camara_gnomeregan",
        name       = "[ÉLITE] Cámara Sellada de Gnomeregan",
        desc       = "Un sector irradiado de Gnomeregan esconde tecnología prototipo de alto valor. El lépero jefe que guarda la cámara es enormemente resistente. Se requiere coordinación táctica y equipo anti-radiación.",
        minLevel   = 22,
        maxLevel   = 28,
        difficulty = "ELITE",
        duration   = 1500,
        goldMin    = 22000,
        goldMax    = 45000,
        icon       = "Interface\\Icons\\INV_Gizmo_GoblinAirToGroundRocket",
    },

    -- ─── NIVEL 31-40 ─────────────────────────────────────────
    {
        id         = "q_convoy_royal",
        name       = "Convoy Real",
        desc       = "Protege el convoy real a través de territorio peligroso.",
        minLevel   = 31,
        maxLevel   = 40,
        difficulty = "HARD",
        duration   = BotQuestData.DURATIONS.LONG,
        goldMin    = 4000,
        goldMax    = 8000,
        icon       = "Interface\\Icons\\inv_shield_13",
    },
    {
        id         = "q_fortaleza_gnoll",
        name       = "Fortaleza Gnoll",
        desc       = "Los gnolls han levantado una fortaleza. Derriba sus defensas.",
        minLevel   = 35,
        maxLevel   = 40,
        difficulty = "HARD",
        duration   = BotQuestData.DURATIONS.LONG,
        goldMin    = 5000,
        goldMax    = 10000,
        icon       = "Interface\\Icons\\Ability_Warrior_Rampage",
    },
    {
        id         = "q_arenas_stranglethorn",
        name       = "Cacería en Vega de Tuercespina",
        desc       = "Embosca a los jugadores y bots de la otra facción en el mapa de mundo abierto más sangriento.",
        minLevel   = 32,
        maxLevel   = 40,
        difficulty = "HARD",
        duration   = BotQuestData.DURATIONS.LONG,
        goldMin    = 4500,
        goldMax    = 9000,
        icon       = "Interface\\Icons\\INV_Weapon_ShortBlade_21",
        isPvP      = true,
        honorPoints= 500,
    },
    {
        id         = "q_piratas_tanaris",
        name       = "Corsarios de Tanaris",
        desc       = "Asalta los navíos piratas que atracaron en las costas del desierto.",
        minLevel   = 33,
        maxLevel   = 40,
        difficulty = "NORMAL",
        duration   = BotQuestData.DURATIONS.MEDIUM,
        goldMin    = 4200,
        goldMax    = 8500,
        icon       = "Interface\\Icons\\INV_Helmet_66",
    },
    {
        id         = "q_monasterio_infiltracion",
        name       = "Infiltración Escarlata",
        desc       = "Envía a tus bots a robar los manuscritos secretos guardados celosamente en el monasterio.",
        minLevel   = 36,
        maxLevel   = 40,
        difficulty = "HARD",
        duration   = BotQuestData.DURATIONS.LONG,
        goldMin    = 5200,
        goldMax    = 11000,
        icon       = "Interface\\Icons\\Spell_Holy_PrayerOfHealing",
    },
    {
        id         = "q_garganta_grito_guerra_med",
        name       = "Guerra de Clanes (Grito de Guerra)",
        desc       = "La contienda en el cañón se intensifica. Consigue una victoria aplastante.",
        minLevel   = 38,
        maxLevel   = 40,
        difficulty = "HARD",
        duration   = BotQuestData.DURATIONS.LONG,
        goldMin    = 5500,
        goldMax    = 12000,
        icon       = "Interface\\Icons\\Spell_Nature_Thorns",
        isPvP      = true,
        honorPoints= 600,
    },
    {
        id         = "q_elementales_tierras_altas",
        name       = "Calamidad Elemental",
        desc       = "Cierra las brechas mágicas que están liberando elementales furiosos en la meseta.",
        minLevel   = 34,
        maxLevel   = 40,
        difficulty = "NORMAL",
        duration   = BotQuestData.DURATIONS.MEDIUM,
        goldMin    = 4300,
        goldMax    = 8800,
        icon       = "Interface\\Icons\\Spell_Frost_SummonWaterElemental",
    },
    {
        id         = "q_ruinas_milenarias",
        name       = "El Ídolo de Piedra",
        desc       = "Recupera una enorme reliquia antes de que los trols locales terminen su ritual de sacrificio.",
        minLevel   = 39,
        maxLevel   = 40,
        difficulty = "ELITE",
        duration   = BotQuestData.DURATIONS.EPIC,
        goldMin    = 6000,
        goldMax    = 13000,
        icon       = "Interface\\Icons\\INV_Misc_Statue_01",
    },

    -- ─── ÉLITE 31-37 ─────────────────────────────────────────
    {
        id         = "q_elite_morshan_contraataque",
        name       = "[ÉLITE] Fortaleza Mor'shan: Contraataque",
        desc       = "Un clan de trolls de Zul'Farrak ha enviado una vanguardia para asaltar la Fortaleza Mor'shan. Los refuerzos tardarán demasiado. Tu escuadrón debe contener la oleada y eliminar al jefe de guerra troll.",
        minLevel   = 31,
        maxLevel   = 37,
        difficulty = "ELITE",
        duration   = 1800,
        goldMin    = 35000,
        goldMax    = 65000,
        icon       = "Interface\\Icons\\Ability_Warrior_Sunder",
    },
    {
        id         = "q_elite_sombra_serenos_solares",
        name       = "[ÉLITE] La Sombra de los Serenos Solares",
        desc       = "Espías de los Serenos Solares han robado artefactos de luz sagrada de un templo de la Alianza. Infiltra su campamento en Desolace, recupera los artefactos y neutraliza al agente infiltrado antes de que huya.",
        minLevel   = 31,
        maxLevel   = 37,
        difficulty = "ELITE",
        duration   = 2100,
        goldMin    = 40000,
        goldMax    = 75000,
        icon       = "Interface\\Icons\\Spell_Holy_MindVision",
    },

    -- ─── NIVEL 41-50 ─────────────────────────────────────────
    {
        id         = "q_minas_profundas",
        name       = "Las Minas Profundas",
        desc       = "Criaturas desconocidas emergen de las minas. Investiga y elimina la amenaza.",
        minLevel   = 41,
        maxLevel   = 50,
        difficulty = "HARD",
        duration   = BotQuestData.DURATIONS.LONG,
        goldMin    = 10000,
        goldMax    = 20000,
        icon       = "Interface\\Icons\\inv_misc_ammo_gunpowder_04",
    },
    {
        id         = "q_retomar_puesto",
        name       = "Retomar el Puesto",
        desc       = "Un puesto avanzado fue tomado por el enemigo. Recupéralo a cualquier precio.",
        minLevel   = 45,
        maxLevel   = 50,
        difficulty = "ELITE",
        duration   = BotQuestData.DURATIONS.EPIC,
        goldMin    = 15000,
        goldMax    = 30000,
        icon       = "Interface\\Icons\\Ability_Warrior_InnerRage",
    },
    {
        id         = "q_cuenca_arathi_med",
        name       = "Conflicto por las Tierras Altas",
        desc       = "Establece control absoluto sobre el aserradero y la mina en la Cuenca de Arathi.",
        minLevel   = 41,
        maxLevel   = 50,
        difficulty = "HARD",
        duration   = BotQuestData.DURATIONS.LONG,
        goldMin    = 11000,
        goldMax    = 22000,
        icon       = "Interface\\Icons\\Ability_TrueShot",
        isPvP      = true,
        honorPoints= 800,
    },
    {
        id         = "q_escaramuza_gadgetzan",
        name       = "Venganza en Gadgetzan",
        desc       = "Caza a los renegados enemigos que merodean los límites de la ciudad neutral.",
        minLevel   = 43,
        maxLevel   = 50,
        difficulty = "NORMAL",
        duration   = BotQuestData.DURATIONS.MEDIUM,
        goldMin    = 10500,
        goldMax    = 21000,
        icon       = "Interface\\Icons\\Spell_Shadow_AnimateDead",
        isPvP      = true,
        honorPoints= 750,
    },
    {
        id         = "q_ruinas_zulfarrak",
        name       = "Alrededores de Sandfury",
        desc       = "Los trols de las arenas preparan un ataque masivo. Sabotea sus fuentes de agua.",
        minLevel   = 44,
        maxLevel   = 50,
        difficulty = "NORMAL",
        duration   = BotQuestData.DURATIONS.MEDIUM,
        goldMin    = 12000,
        goldMax    = 24000,
        icon       = "Interface\\Icons\\INV_Drink_06",
    },
    {
        id         = "q_demonios_felwood",
        name       = "Corrupción en Felwood",
        desc       = "Saca la esencia corrupta de los satiros que deambulan los bosques marchitos.",
        minLevel   = 46,
        maxLevel   = 50,
        difficulty = "NORMAL",
        duration   = BotQuestData.DURATIONS.MEDIUM,
        goldMin    = 13000,
        goldMax    = 26000,
        icon       = "Interface\\Icons\\Spell_Shadow_SummonFelhunter",
    },
    {
        id         = "q_golem_tierras_interiores",
        name       = "Golems de Hinterlands",
        desc       = "Destruye los constructos rúnicos que los enanos u orcos salvajes han dejado sin control.",
        minLevel   = 42,
        maxLevel   = 50,
        difficulty = "EASY",
        duration   = BotQuestData.DURATIONS.SHORT,
        goldMin    = 9500,
        goldMax    = 19000,
        icon       = "Interface\\Icons\\INV_Misc_Gear_01",
    },
    {
        id         = "q_ojo_gorgona",
        name       = "El Nido de las Harpías",
        desc       = "Sube a los riscos más altos de Feralas y elimina a la matriarca de las harpías.",
        minLevel   = 48,
        maxLevel   = 50,
        difficulty = "ELITE",
        duration   = BotQuestData.DURATIONS.EPIC,
        goldMin    = 17000,
        goldMax    = 35000,
        icon       = "Interface\\Icons\\INV_Feather_03",
    },

    -- ─── ÉLITE 40-45 ─────────────────────────────────────────
    {
        id         = "q_elite_catacumbas_maraudon",
        name       = "[ÉLITE] Las Catacumbas de Marrón Carmesí",
        desc       = "Bajo las ruinas de Maraudon yace una cámara sellada con una entidad corrupta de la naturaleza. El grupo deberá atravesar varias oleadas de guardianes elementales antes de enfrentarla. La corrupción afecta el entorno.",
        minLevel   = 40,
        maxLevel   = 45,
        difficulty = "ELITE",
        duration   = 2400,
        goldMin    = 65000,
        goldMax    = 120000,
        icon       = "Interface\\Icons\\Spell_Nature_NatureTouchGrow",
    },
    {
        id         = "q_elite_escolta_convoy_real",
        name       = "[ÉLITE] Escolta del Convoy Real",
        desc       = "Un convoy con suministros críticos para el frente de guerra debe atravesar las Tierras Inhóspitas, un corredor infestado por gnolls de élite y bandidos mercenarios. Protégelo hasta el destino sin bajas.",
        minLevel   = 40,
        maxLevel   = 45,
        difficulty = "ELITE",
        duration   = 2700,
        goldMin    = 70000,
        goldMax    = 130000,
        icon       = "Interface\\Icons\\Ability_Defend",
    },

    -- ─── ÉLITE 45-52 ─────────────────────────────────────────
    {
        id         = "q_elite_heraldo_llama_negra",
        name       = "[ÉLITE] El Heraldo de la Llama Negra",
        desc       = "Un heraldo de Ragnaros ha sido avistado en las Tierras de Fuego exteriores coordinando ataques contra asentamientos enanos. Intercepta su ritual antes de que convoque refuerzos desde el Núcleo de Magma.",
        minLevel   = 45,
        maxLevel   = 52,
        difficulty = "ELITE",
        duration   = 2700,
        goldMin    = 90000,
        goldMax    = 175000,
        icon       = "Interface\\Icons\\Spell_Fire_FireBolt02",
    },
    {
        id         = "q_elite_prision_vientos_fuga",
        name       = "[ÉLITE] Prisión de los Vientos: Fuga",
        desc       = "Un peligroso arúspice de los Vientos del Norte ha escapado de su celda en Alterac. Su rastro de magia elemental devastadora debe cortarse antes de que alcance a sus cómplices en las montañas.",
        minLevel   = 45,
        maxLevel   = 52,
        difficulty = "ELITE",
        duration   = 3000,
        goldMin    = 100000,
        goldMax    = 190000,
        icon       = "Interface\\Icons\\Spell_Frost_FrostBolt02",
    },

    -- ─── NIVEL 51-60 ─────────────────────────────────────────
    {
        id         = "q_plaga_pantano",
        name       = "La Plaga del Pantano",
        desc       = "Algo corrompe las aguas del pantano. Busca el origen y destrúyelo.",
        minLevel   = 51,
        maxLevel   = 60,
        difficulty = "ELITE",
        duration   = BotQuestData.DURATIONS.EPIC,
        goldMin    = 30000,
        goldMax    = 60000,
        icon       = "Interface\\Icons\\Spell_Nature_Drowsy",
    },
    {
        id         = "q_guardian_antiguo",
        name       = "El Guardián Antiguo",
        desc       = "Un ser ancestral ha despertado y siembra el caos. Solo los más valientes se atreven.",
        minLevel   = 58,
        maxLevel   = 60,
        difficulty = "ELITE",
        duration   = BotQuestData.DURATIONS.EPIC,
        goldMin    = 50000,
        goldMax    = 100000,
        icon       = "Interface\\Icons\\Spell_Nature_ForceOfNature",
    },
    {
        id         = "q_valle_alterac_clasico",
        name       = "Guerra Total en Alterac",
        desc       = "La batalla definitiva. Destruye los búnkeres, invoca al elemental y ejecuta al general enemigo.",
        minLevel   = 51,
        maxLevel   = 60,
        difficulty = "ELITE",
        duration   = BotQuestData.DURATIONS.EPIC,
        goldMin    = 45000,
        goldMax    = 95000,
        icon       = "Interface\\Icons\\Achievement_BG_WinAV",
        isPvP      = true,
        honorPoints= 1500,
    },
    {
        id         = "q_silithus_colmenas",
        name       = "Las Colmenas Silítidas",
        desc       = "Infíltrate en los insectarios de Silithus y acaba con los bichos excavadores.",
        minLevel   = 54,
        maxLevel   = 60,
        difficulty = "HARD",
        duration   = BotQuestData.DURATIONS.LONG,
        goldMin    = 35000,
        goldMax    = 70000,
        icon       = "Interface\\Icons\\INV_Misc_Eye_01",
    },
    {
        id         = "q_tierras_peste_este",
        name       = "Torres de las Tierras de la Peste",
        desc       = "Captura las torres de vigilancia para debilitar la presencia de la facción contraria en la zona.",
        minLevel   = 55,
        maxLevel   = 60,
        difficulty = "HARD",
        duration   = BotQuestData.DURATIONS.LONG,
        goldMin    = 38000,
        goldMax    = 80000,
        icon       = "Interface\\Icons\\INV_BannerPVP_02",
        isPvP      = true,
        honorPoints= 1200,
    },
    {
        id         = "q_invocacion_rocanegra",
        name       = "Espías en la Roca Negra",
        desc       = "Vigila la entrada de la Montaña Roca Negra y liquida a las patrullas orcas del clan competidor.",
        minLevel   = 52,
        maxLevel   = 60,
        difficulty = "NORMAL",
        duration   = BotQuestData.DURATIONS.MEDIUM,
        goldMin    = 32000,
        goldMax    = 65000,
        icon       = "Interface\\Icons\\Spell_Fire_SelfDestruct",
    },
    {
        id         = "q_escaramuza_bruma",
        name       = "Invasión en Tierras de la Peste",
        desc       = "Combate directo contra las fuerzas de élite enemigas en las ruinas de Stratholme exterior.",
        minLevel   = 56,
        maxLevel   = 60,
        difficulty = "HARD",
        duration   = BotQuestData.DURATIONS.LONG,
        goldMin    = 40000,
        goldMax    = 85000,
        icon       = "Interface\\Icons\\Spell_Shadow_DeathPact",
        isPvP      = true,
        honorPoints= 1300,
    },
    {
        id         = "q_invierno_cuna",
        name       = "Gigantes de Cuna de Invierno",
        desc       = "Elimina a los gigantes de hielo que congelan las rutas de comercio neutrales.",
        minLevel   = 57,
        maxLevel   = 60,
        difficulty = "NORMAL",
        duration   = BotQuestData.DURATIONS.MEDIUM,
        goldMin    = 36000,
        goldMax    = 75000,
        icon       = "Interface\\Icons\\achievement_dungeon_ulduarraid_ironsentinel_01",
    },

    -- ─── NIVEL 61-70 (Outland) ────────────────────────────────
    {
        id         = "q_patrulla_terrallende",
        name       = "Patrulla en Terrallende",
        desc       = "Los demonios no descansan. Mantén el perímetro del portal bajo control.",
        minLevel   = 61,
        maxLevel   = 70,
        difficulty = "HARD",
        duration   = BotQuestData.DURATIONS.LONG,
        goldMin    = 60000,
        goldMax    = 120000,
        icon       = "Interface\\Icons\\ability_warlock_haunt",
    },
    {
        id         = "q_torre_mago_negro",
        name       = "La Torre del Mago Negro",
        desc       = "Un brujo ha tomado una torre estratégica. Asáltala y elimínalo.",
        minLevel   = 65,
        maxLevel   = 70,
        difficulty = "ELITE",
        duration   = BotQuestData.DURATIONS.EPIC,
        goldMin    = 100000,
        goldMax    = 200000,
        icon       = "Interface\\Icons\\Spell_Shadow_DeathCoil",
    },
    {
        id         = "q_ojo_tormenta",
        name       = "Dominio en el Ojo de la Tormenta",
        desc       = "Cruza los puentes flotantes de Tormenta Abisal. Mantén las torres y captura la runa central.",
        minLevel   = 61,
        maxLevel   = 70,
        difficulty = "HARD",
        duration   = BotQuestData.DURATIONS.LONG,
        goldMin    = 70000,
        goldMax    = 140000,
        icon       = "Interface\\Icons\\inv_misc_tournaments_banner_bloodelf",
        isPvP      = true,
        honorPoints= 2000,
    },
    {
        id         = "q_ciudadelas_fuego_infernal",
        name       = "Fortificaciones de la Península",
        desc       = "Asalta los tres puntos de control clave en el mapa de la Península del Fuego Infernal.",
        minLevel   = 62,
        maxLevel   = 70,
        difficulty = "NORMAL",
        duration   = BotQuestData.DURATIONS.MEDIUM,
        goldMin    = 65000,
        goldMax    = 130000,
        icon       = "Interface\\Icons\\Spell_Holy_MindVision",
        isPvP      = true,
        honorPoints= 1800,
    },
    {
        id         = "q_marisma_zangar_esporas",
        name       = "Gigantes de la Marisma",
        desc       = "Consigue los fluidos vitales de los caminantes fúngicos gigantes de Marisma de Zangar.",
        minLevel   = 63,
        maxLevel   = 70,
        difficulty = "EASY",
        duration   = BotQuestData.DURATIONS.SHORT,
        goldMin    = 55000,
        goldMax    = 110000,
        icon       = "Interface\\Icons\\achievement_dungeon_hordeairship",
    },
    {
        id         = "q_consocio_nagrand",
        name       = "Guerra de Bandas en Halaa",
        desc       = "Combate a campo abierto para reclamar el control de la ciudad fortificada de Halaa.",
        minLevel   = 66,
        maxLevel   = 70,
        difficulty = "HARD",
        duration   = BotQuestData.DURATIONS.LONG,
        goldMin    = 85000,
        goldMax    = 170000,
        icon       = "Interface\\Icons\\INV_BannerPVP_03",
        isPvP      = true,
        honorPoints= 2200,
    },
    {
        id         = "q_terrazas_skettis",
        name       = "Los Cielos de Skettis",
        desc       = "Derriba a los jinetes de kaliri y destruye los huevos de los hombres pájaro.",
        minLevel   = 68,
        maxLevel   = 70,
        difficulty = "NORMAL",
        duration   = BotQuestData.DURATIONS.MEDIUM,
        goldMin    = 80000,
        goldMax    = 160000,
        icon       = "Interface\\Icons\\ability_hunter_pet_dragonhawk",
    },
    {
        id         = "q_sol_devastado",
        name       = "Frente de la Isla de Quel'Danas",
        desc       = "Cumple misiones de sabotaje contra las fuerzas de Kael'thas en los muelles.",
        minLevel   = 70,
        maxLevel   = 70,
        difficulty = "ELITE",
        duration   = BotQuestData.DURATIONS.EPIC,
        goldMin    = 120000,
        goldMax    = 250000,
        icon       = "Interface\\Icons\\Spell_Holy_MagicalSentry",
    },

    -- ─── NIVEL 71-80 (Northrend) ──────────────────────────────
    {
        id         = "q_vanguardia_rasganorte",
        name       = "Vanguardia en Rasganorte",
        desc       = "La Plaga avanza. Detén la oleada antes de que llegue al campamento base.",
        minLevel   = 71,
        maxLevel   = 80,
        difficulty = "HARD",
        duration   = BotQuestData.DURATIONS.LONG,
        goldMin    = 150000,
        goldMax    = 300000,
        icon       = "Interface\\Icons\\Spell_Frost_FrostShock",
    },
    {
        id         = "q_cripta_helada",
        name       = "La Cripta Helada",
        desc       = "Los no-muertos se agitan en la cripta. Séllala antes del amanecer.",
        minLevel   = 75,
        maxLevel   = 80,
        difficulty = "ELITE",
        duration   = BotQuestData.DURATIONS.EPIC,
        goldMin    = 250000,
        goldMax    = 500000,
        icon       = "Interface\\Icons\\Spell_DeathKnight_IcyTalons",
    },
    {
        id         = "q_citadela_sombria",
        name       = "Asalto a la Ciudadela Sombría",
        desc       = "Misión suicida en el corazón del territorio del Rey Exánime. Solo los legendarios regresan.",
        minLevel   = 80,
        maxLevel   = nil,
        difficulty = "ELITE",
        duration   = BotQuestData.DURATIONS.EPIC,
        goldMin    = 500000,
        goldMax    = 1000000,
        icon       = "Interface\\Icons\\Achievement_Boss_LichKing",
    },
    {
        id         = "q_conquista_invierno",
        name       = "Conquista del Invierno",
        desc       = "¡La fortaleza está bajo asedio! Conduce vehículos de guerra y destruye los muros enemigos.",
        minLevel   = 78,
        maxLevel   = 80,
        difficulty = "ELITE",
        duration   = BotQuestData.DURATIONS.EPIC,
        goldMin    = 400000,
        goldMax    = 850000,
        icon       = "Interface\\Icons\\achievement_pvp_o_12",
        isPvP      = true,
        honorPoints= 4000,
    },
    {
        id         = "q_playa_ancestros",
        name       = "Playa de los Ancestros",
        desc       = "Asalta las playas usando las reliquias de titán y los demoledores de asedio.",
        minLevel   = 71,
        maxLevel   = 80,
        difficulty = "HARD",
        duration   = BotQuestData.DURATIONS.LONG,
        goldMin    = 200000,
        goldMax    = 450000,
        icon       = "Interface\\Icons\\achievement_pvp_p_06",
        isPvP      = true,
        honorPoints= 2500,
    },
    {
        id         = "q_naxxramas_alrededores",
        name       = "La Sombra de Naxxramas",
        desc       = "Destruye a las gárgolas de plaga que custodian el cielo de Cementerio de Dragones.",
        minLevel   = 73,
        maxLevel   = 80,
        difficulty = "NORMAL",
        duration   = BotQuestData.DURATIONS.MEDIUM,
        goldMin    = 180000,
        goldMax    = 380000,
        icon       = "Interface\\Icons\\Spell_Shadow_GatherShadows",
    },
    {
        id         = "q_colmillarr_pesca",
        name       = "Suministros Kalu'ak",
        desc       = "Ayuda a los mofletones pescadores defendiendo sus trampas contra los feroces piratas marinos.",
        minLevel   = 72,
        maxLevel   = 80,
        difficulty = "EASY",
        duration   = BotQuestData.DURATIONS.SHORT,
        goldMin    = 160000,
        goldMax    = 320000,
        icon       = "Interface\\Icons\\Trade_Fishing",
    },
    {
        id         = "q_picos_tormentosos_gigantes",
        name       = "Los Hijos de Hodir",
        desc       = "Derrota a los gigantes de escarcha rebeldes para ganarte el respeto de los señores del trueno.",
        minLevel   = 77,
        maxLevel   = 80,
        difficulty = "HARD",
        duration   = BotQuestData.DURATIONS.LONG,
        goldMin    = 300000,
        goldMax    = 600000,
        icon       = "Interface\\Icons\\achievement_zone_icecrown_03",
    },
    {
        id         = "q_torneo_argenteo",
        name       = "Justas en el Torneo Argenteo",
        desc       = "Monta tu corcel de batalla y derrota en una justa de honor a los campeones de la otra facción.",
        minLevel   = 80,
        maxLevel   = nil,
        difficulty = "HARD",
        duration   = BotQuestData.DURATIONS.LONG,
        goldMin    = 450000,
        goldMax    = 900000,
        icon       = "Interface\\Icons\\Ability_Mount_WhiteDireWolf",
        isPvP      = true,
        honorPoints= 3500,
    },

-- ============================================================
    --  EXPANSIÓN DE MISIONES (10 POR RANGO DE NIVEL)
    -- ============================================================

    -- ─── NIVEL 1-10 (10 Misiones) ───────────────────────────
    {
        id         = "q_eco_islas",
        name       = "Limpieza en las Islas del Eco",
        desc       = "Los tigres y ratiyas locales están descontrolados. Ayuda a asegurar la zona de inicio.",
        minLevel   = 1,
        maxLevel   = 10,
        difficulty = "EASY",
        duration   = BotQuestData.DURATIONS.SHORT,
        goldMin    = 50,
        goldMax    = 210,
        icon       = "Interface\\Icons\\ability_hunter_pet_cat",
    },
    {
        id         = "q_infestacion_viejas",
        name       = "Plaga en los Viñedos",
        desc       = "Las arañas han anidado cerca de las tierras de cultivo del sur. Quema sus sacos de huevos.",
        minLevel   = 2,
        maxLevel   = 10,
        difficulty = "EASY",
        duration   = BotQuestData.DURATIONS.SHORT,
        goldMin    = 60,
        goldMax    = 230,
        icon       = "Interface\\Icons\\INV_Misc_Bone_08",
    },
    {
        id         = "q_recolectar_cardos",
        name       = "Cardos para los Alquimistas",
        desc       = "Los botánicos locales necesitan muestras de plantas que crecen cerca de los nidos de los kóbolds.",
        minLevel   = 3,
        maxLevel   = 10,
        difficulty = "EASY",
        duration   = BotQuestData.DURATIONS.SHORT,
        goldMin    = 55,
        goldMax    = 225,
        icon       = "Interface\\Icons\\INV_Misc_Herb_01",
    },
    {
        id         = "q_troggs_valle",
        name       = "Invasión de Troggs",
        desc       = "Los troggs han salido de sus cuevas e interrumpen las operaciones de excavación de los enanos.",
        minLevel   = 4,
        maxLevel   = 10,
        difficulty = "NORMAL",
        duration   = BotQuestData.DURATIONS.MEDIUM,
        goldMin    = 110,
        goldMax    = 310,
        icon       = "Interface\\Icons\\INV_Helmet_06",
    },
    {
        id         = "q_desafio_gnoll",
        name       = "Los Clanes Gnoll",
        desc       = "Los gnolls Garrapata se están agrupando. Elimina a sus exploradores antes de que organicen un ataque.",
        minLevel   = 5,
        maxLevel   = 10,
        difficulty = "NORMAL",
        duration   = BotQuestData.DURATIONS.MEDIUM,
        goldMin    = 115,
        goldMax    = 320,
        icon       = "Interface\\Icons\\inv_misc_bandana_01",
    },
    {
        id         = "q_emboscada_camino",
        name       = "Vigilancia en el Camino Real",
        desc       = "Protege las caravanas de suministros de los asaltantes nocturnos que se esconden en los arbustos.",
        minLevel   = 5,
        maxLevel   = 10,
        difficulty = "NORMAL",
        duration   = BotQuestData.DURATIONS.MEDIUM,
        goldMin    = 130,
        goldMax    = 340,
        icon       = "Interface\\Icons\\Ability_Ambush",
    },
    {
        id         = "q_reliquia_ancestral",
        name       = "La Reliquia Perdida",
        desc       = "Recupera un antiguo tomo de magia que fue robado de la abadía/academia local por cultistas.",
        minLevel   = 6,
        maxLevel   = 10,
        difficulty = "NORMAL",
        duration   = BotQuestData.DURATIONS.MEDIUM,
        goldMin    = 140,
        goldMax    = 360,
        icon       = "Interface\\Icons\\INV_Misc_Book_09",
    },
    {
        id         = "q_defensa_frontera_pvp",
        name       = "Escaramuza en la Frontera",
        desc       = "Fuerzas de exploración enemigas merodean las zonas de inicio. Repele la intrusión de la otra facción.",
        minLevel   = 7,
        maxLevel   = 10,
        difficulty = "HARD",
        duration   = BotQuestData.DURATIONS.LONG,
        goldMin    = 180,
        goldMax    = 450,
        icon       = "Interface\\Icons\\INV_BannerPVP_01",
        isPvP      = true,
        honorPoints= 60,
    },
    {
        id         = "q_lider_cangrejos",
        name       = "Garras de la Costa",
        desc       = "Un enorme crustáceo mutado está aterrorizando a los pescadores en las playas. Elimínalo.",
        minLevel   = 8,
        maxLevel   = 10,
        difficulty = "HARD",
        duration   = BotQuestData.DURATIONS.LONG,
        goldMin    = 190,
        goldMax    = 480,
        icon       = "Interface\\Icons\\INV_Misc_MonsterClaw_04",
    },
    {
        id         = "q_jefe_murloc",
        name       = "El Rey de los Murlocs",
        desc       = "Organiza una incursión al campamento murloc principal de la costa y acaba con su chamán líder.",
        minLevel   = 9,
        maxLevel   = 10,
        difficulty = "ELITE",
        duration   = BotQuestData.DURATIONS.EPIC,
        goldMin    = 250,
        goldMax    = 600,
        icon       = "Interface\\Icons\\inv_box_petcarrier_01",
    },

    -- ─── NIVEL 11-20 (10 Misiones) ──────────────────────────
    {
        id         = "q_cosechadores_poniente",
        name       = "Cosechadores de la Muerte",
        desc       = "Los golems mecánicos de las cosechas se han vuelto locos. Desmárcalos antes de que destrocen el trigo.",
        minLevel   = 11,
        maxLevel   = 20,
        difficulty = "EASY",
        duration   = BotQuestData.DURATIONS.SHORT,
        goldMin    = 420,
        goldMax    = 850,
        icon       = "Interface\\Icons\\INV_Misc_Bone_HumanSkull_01",
    },
    {
        id         = "q_oasis_barrenos",
        name       = "Los Oasis Ocultos",
        desc       = "Recoge muestras de agua de los oasis de Los Barrenos para investigar la flora mutada.",
        minLevel   = 12,
        maxLevel   = 20,
        difficulty = "EASY",
        duration   = BotQuestData.DURATIONS.SHORT,
        goldMin    = 440,
        goldMax    = 880,
        icon       = "Interface\\Icons\\INV_Drink_02",
    },
    {
        id         = "q_goblins_fundicion",
        name       = "Sabotaje en la Fundición",
        desc       = "La Compañía Ventura está talando árboles ilegalmente. Roba las piezas de sus trituradoras.",
        minLevel   = 13,
        maxLevel   = 20,
        difficulty = "NORMAL",
        duration   = BotQuestData.DURATIONS.MEDIUM,
        goldMin    = 500,
        goldMax    = 1100,
        icon       = "Interface\\Icons\\Trade_Engineering",
    },
    {
        id         = "q_murlocs_ashenvale",
        name       = "Cacería en la Costa de Darkshore",
        desc       = "Los murlocs de las playas del norte tienen artefactos antiguos robados de los elfos. Recupéralos.",
        minLevel   = 14,
        maxLevel   = 20,
        difficulty = "NORMAL",
        duration   = BotQuestData.DURATIONS.MEDIUM,
        goldMin    = 520,
        goldMax    = 1150,
        icon       = "Interface\\Icons\\ability_hunter_pet_crab",
    },
    {
        id         = "q_arpías_charca",
        name       = "Garras de los Riscos",
        desc       = "Las arpías del cañón están atacando a los jinetes de viento. Limpia sus nidos en las alturas.",
        minLevel   = 15,
        maxLevel   = 20,
        difficulty = "NORMAL",
        duration   = BotQuestData.DURATIONS.MEDIUM,
        goldMin    = 540,
        goldMax    = 1250,
        icon       = "Interface\\Icons\\INV_Feather_05",
    },
    {
        id         = "q_minas_muertas_ext",
        name       = "Los Guardias Defias",
        desc       = "Elimina las patrullas que vigilan las entradas ocultas de los túneles de los bandidos.",
        minLevel   = 16,
        maxLevel   = 20,
        difficulty = "NORMAL",
        duration   = BotQuestData.DURATIONS.MEDIUM,
        goldMin    = 580,
        goldMax    = 1300,
        icon       = "Interface\\Icons\\INV_Shirt_Red_01",
    },
    {
        id         = "q_defensa_puesto_ashenvale",
        name       = "Frente Forestal JcJ",
        desc       = "Ashenvale arde. Asalta el puesto de control de la facción contraria en el bosque profundo.",
        minLevel   = 17,
        maxLevel   = 20,
        difficulty = "HARD",
        duration   = BotQuestData.DURATIONS.LONG,
        goldMin    = 750,
        goldMax    = 1650,
        icon       = "Interface\\Icons\\Ability_Warrior_WarCry",
        isPvP      = true,
        honorPoints= 180,
    },
    {
        id         = "q_sombras_colmilloscuro",
        name       = "Maldición de los Hombres Lobo",
        desc       = "Los huargen del Castillo de Colmillo Oscuro se extienden por los bosques de Argénteos. Cázalos.",
        minLevel   = 18,
        maxLevel   = 20,
        difficulty = "HARD",
        duration   = BotQuestData.DURATIONS.LONG,
        goldMin    = 780,
        goldMax    = 1700,
        icon       = "Interface\\Icons\\Spell_Shadow_GatherShadows",
    },
    {
        id         = "q_excavacion_baja",
        name       = "Los Fósiles de Bael Modan",
        desc       = "Recupera reliquias rúnicas excavadas por enanos antes de que destruyan el Lore local.",
        minLevel   = 19,
        maxLevel   = 20,
        difficulty = "HARD",
        duration   = BotQuestData.DURATIONS.LONG,
        goldMin    = 820,
        goldMax    = 1750,
        icon       = "Interface\\Icons\\INV_Misc_Bone_02",
    },
    {
        id         = "q_jefe_defias",
        name       = "El Capataz de la Fundición",
        desc       = "Infíltrate en el centro logístico criminal y ejecuta al ingeniero jefe de los bandidos.",
        minLevel   = 20,
        maxLevel   = 20,
        difficulty = "ELITE",
        duration   = BotQuestData.DURATIONS.EPIC,
        goldMin    = 1000,
        goldMax    = 2200,
        icon       = "Interface\\Icons\\Trade_Engineering",
    },

    -- ─── NIVEL 21-30 (10 Misiones) ──────────────────────────
    {
        id         = "q_cementerio_duskwood",
        name       = "Las Sombras de Raven Hill",
        desc       = "Los esqueletos caminan por el cementerio de Duskwood. Pon fin a su tormento eterno.",
        minLevel   = 21,
        maxLevel   = 30,
        difficulty = "EASY",
        duration   = BotQuestData.DURATIONS.SHORT,
        goldMin    = 1050,
        goldMax    = 2200,
        icon       = "Interface\\Icons\\ability_druid_forceofnature",
    },
    {
        id         = "q_recolectar_raices",
        name       = "Raíces de los Humedales",
        desc       = "Consigue tubérculos pantanosos raros custodiados por los feroces crocoliscos.",
        minLevel   = 22,
        maxLevel   = 30,
        difficulty = "EASY",
        duration   = BotQuestData.DURATIONS.SHORT,
        goldMin    = 1100,
        goldMax    = 2300,
        icon       = "Interface\\Icons\\INV_Misc_Herb_10",
    },
    {
        id         = "q_escaramuza_trabalomas",
        name       = "Disputa en Trabalomas JcJ",
        desc       = "La histórica rivalidad entre Costasur y Molino de Tarren revive. Ejecuta campeones enemigos.",
        minLevel   = 23,
        maxLevel   = 30,
        difficulty = "HARD",
        duration   = BotQuestData.DURATIONS.LONG,
        goldMin    = 1600,
        goldMax    = 3400,
        icon       = "Interface\\Icons\\Ability_Warrior_Revenge",
        isPvP      = true,
        honorPoints= 280,
    },
    {
        id         = "q_trols_stranglethorn_baja",
        name       = "Las Ruinas de Zul'Kunda",
        desc       = "Los trols Singapur están reuniendo pociones de vudú. Sabotea sus calderos.",
        minLevel   = 24,
        maxLevel   = 30,
        difficulty = "NORMAL",
        duration   = BotQuestData.DURATIONS.MEDIUM,
        goldMin    = 1300,
        goldMax    = 2900,
        icon       = "Interface\\Icons\\INV_Potion_21",
    },
    {
        id         = "q_enanos_dunmodr",
        name       = "El Asedio de Dun Modr",
        desc       = "Los enanos Hierro Negro han sitiado el puente del norte. Limpia las barricadas.",
        minLevel   = 25,
        maxLevel   = 30,
        difficulty = "NORMAL",
        duration   = BotQuestData.DURATIONS.MEDIUM,
        goldMin    = 1400,
        goldMax    = 3100,
        icon       = "Interface\\Icons\\INV_Shield_04",
    },
    {
        id         = "q_orcos_redridge",
        name       = "La Amenaza de Crestagrana",
        desc       = "Los orcos del clan Roca Negra han tomado las fortalezas del este. Reduce sus filas.",
        minLevel   = 26,
        maxLevel   = 30,
        difficulty = "NORMAL",
        duration   = BotQuestData.DURATIONS.MEDIUM,
        goldMin    = 1500,
        goldMax    = 3300,
        icon       = "Interface\\Icons\\INV_Axe_02",
    },
    {
        id         = "q_centauros_desolace_baja",
        name       = "Guerra de Clanes en Desolace",
        desc       = "Elige un bando implícitamente atacando las líneas de suministros de los centauros Kolkar.",
        minLevel   = 27,
        maxLevel   = 30,
        difficulty = "NORMAL",
        duration   = BotQuestData.DURATIONS.MEDIUM,
        goldMin    = 1650,
        goldMax    = 3600,
        icon       = "Interface\\Icons\\INV_Spear_06",
    },
    {
        id         = "q_elementales_thousand_needles",
        name       = "Calamidad en las Salinas",
        desc       = "Elementales de tierra y aire bloquean las pistas de carreras de los gnomos. Despéchalos.",
        minLevel   = 28,
        maxLevel   = 30,
        difficulty = "HARD",
        duration   = BotQuestData.DURATIONS.LONG,
        goldMin    = 2100,
        goldMax    = 4200,
        icon       = "Interface\\Icons\\Spell_Nature_Earthquake",
    },
    {
        id         = "q_reliquia_sholomance_baja",
        name       = "Fragmentos de Almas",
        desc       = "Los nigromantes están extrayendo almas en cementerios locales. Recupera las gemas rúnicas.",
        minLevel   = 29,
        maxLevel   = 30,
        difficulty = "HARD",
        duration   = BotQuestData.DURATIONS.LONG,
        goldMin    = 2300,
        goldMax    = 4500,
        icon       = "Interface\\Icons\\Spell_Shadow_ShadowWordPain",
    },
    {
        id         = "q_lider_orco_redridge",
        name       = "El Comandante de Crestagrana",
        desc       = "Entra en la torre fortificada de Alther y elimina al capataz ogro que lidera las fuerzas de asedio.",
        minLevel   = 30,
        maxLevel   = 30,
        difficulty = "ELITE",
        duration   = BotQuestData.DURATIONS.EPIC,
        goldMin    = 3200,
        goldMax    = 6500,
        icon       = "Interface\\Icons\\INV_Helmet_32",
    },

    -- ─── NIVEL 31-40 (10 Misiones) ──────────────────────────
    {
        id         = "q_pistas_asfalto",
        name       = "Carreras en Las Mil Agujas",
        desc       = "Los ingenieros goblins necesitan piezas metálicas raras esparcidas por las Salinas.",
        minLevel   = 31,
        maxLevel   = 40,
        difficulty = "EASY",
        duration   = BotQuestData.DURATIONS.SHORT,
        goldMin    = 3800,
        goldMax    = 7500,
        icon       = "Interface\\Icons\\INV_Misc_Wrench_01",
    },
    {
        id         = "q_panteras_tuercespina",
        name       = "Maestría en Caza: Panteras",
        desc       = "Las selvas de Tuercespina son mortales. Caza a las panteras sombrías imperceptibles.",
        minLevel   = 32,
        maxLevel   = 40,
        difficulty = "EASY",
        duration   = BotQuestData.DURATIONS.SHORT,
        goldMin    = 4000,
        goldMax    = 7800,
        icon       = "Interface\\Icons\\Ability_Hunter_Pet_Cat",
    },
    {
        id         = "q_piratas_booty_bay",
        name       = "Los Corsarios de la Vela Roja",
        desc       = "Los piratas amenazan el comercio de Bahía del Botín. Hunde sus barcos quemando sus velas.",
        minLevel   = 33,
        maxLevel   = 40,
        difficulty = "NORMAL",
        duration   = BotQuestData.DURATIONS.MEDIUM,
        goldMin    = 4400,
        goldMax    = 8900,
        icon       = "Interface\\Icons\\INV_Misc_Foot_Centaur",
    },
    {
        id         = "q_dragones_swamp",
        name       = "El Vuelo Verde en el Pantano",
        desc       = "Dragonantes jóvenes se han vuelto agresivos cerca del Templo de Atal'Hakkar. Cázalos.",
        minLevel   = 34,
        maxLevel   = 40,
        difficulty = "NORMAL",
        duration   = BotQuestData.DURATIONS.MEDIUM,
        goldMin    = 4600,
        goldMax    = 9200,
        icon       = "Interface\\Icons\\INV_Misc_Head_Dragon_Green",
    },
    {
        id         = "q_ogros_alterac",
        name       = "Los Ogros de Alterac",
        desc       = "Las ruinas heladas de Alterac están repletas de ogros corpulentos. Limpia las fortificaciones.",
        minLevel   = 35,
        maxLevel   = 40,
        difficulty = "NORMAL",
        duration   = BotQuestData.DURATIONS.MEDIUM,
        goldMin    = 4800,
        goldMax    = 9600,
        icon       = "Interface\\Icons\\ability_druid_lacerate",
    },
    {
        id         = "q_campamento_kurzen",
        name       = "La Locura de Kurzen",
        desc       = "Los soldados renegados de Kurzen se esconden en la jungla. Elimina a sus oficiales médicos.",
        minLevel   = 36,
        maxLevel   = 40,
        difficulty = "NORMAL",
        duration   = BotQuestData.DURATIONS.MEDIUM,
        goldMin    = 5000,
        goldMax    = 10000,
        icon       = "Interface\\Icons\\INV_Misc_Head_Human_02",
    },
    {
        id         = "q_control_minas_arathi_pvp",
        name       = "Control de Canteras JcJ",
        desc       = "La facción rival está extrayendo hierro sagrado en Arathi. Asalta las canteras y elimina jugadores.",
        minLevel   = 37,
        maxLevel   = 40,
        difficulty = "HARD",
        duration   = BotQuestData.DURATIONS.LONG,
        goldMin    = 5600,
        goldMax    = 11500,
        icon       = "Interface\\Icons\\Inv_misc_ear_human_02",
        isPvP      = true,
        honorPoints= 450,
    },
    {
        id         = "q_trols_witherbark",
        name       = "La Tribu Witherbark",
        desc       = "Los trols de las Tierras Altas de Arathi traman un asalto a los refugios. Detenlos.",
        minLevel   = 38,
        maxLevel   = 40,
        difficulty = "HARD",
        duration   = BotQuestData.DURATIONS.LONG,
        goldMin    = 5800,
        goldMax    = 12000,
        icon       = "Interface\\Icons\\INV_Spear_07",
    },
    {
        id         = "q_elementales_desolace",
        name       = "Invocaciones de Maraudon",
        desc       = "Criaturas de tierra corruptas emergen de los valles de Desolace. Destruye sus núcleos.",
        minLevel   = 39,
        maxLevel   = 40,
        difficulty = "HARD",
        duration   = BotQuestData.DURATIONS.LONG,
        goldMin    = 6000,
        goldMax    = 12500,
        icon       = "Interface\\Icons\\Spell_Nature_ResistNature",
    },
    {
        id         = "q_jefe_uaman_tuercespina",
        name       = "El Gran Gorila de la Isla",
        desc       = "Encuentra al gorila alfa albino gigante en las islas del sur de Tuercespina y tráeme su pellejo.",
        minLevel   = 40,
        maxLevel   = 40,
        difficulty = "ELITE",
        duration   = BotQuestData.DURATIONS.EPIC,
        goldMin    = 7500,
        goldMax    = 15000,
        icon       = "Interface\\Icons\\Ability_Hunter_Pet_Gorilla",
    },

    -- ─── NIVEL 41-50 (10 Misiones) ──────────────────────────
    {
        id         = "q_mariscomanos_tanaris",
        name       = "Los Clamores de la Arena",
        desc       = "Los trols Sandfury vigilan ruinas llenas de escarabajos rúnicos. Recolecta sus caparazones.",
        minLevel   = 41,
        maxLevel   = 50,
        difficulty = "EASY",
        duration   = BotQuestData.DURATIONS.SHORT,
        goldMin    = 9000,
        goldMax    = 18000,
        icon       = "Interface\\Icons\\Spell_Frost_WizardMark",
    },
    {
        id         = "q_piratas_tanaris_costa",
        name       = "Los Maleantes de las Dunas",
        desc       = "Los piratas de parajes baldíos han robado los suministros de agua de Gadgetzan. Recupéralos.",
        minLevel   = 42,
        maxLevel   = 50,
        difficulty = "EASY",
        duration   = BotQuestData.DURATIONS.SHORT,
        goldMin    = 9500,
        goldMax    = 19000,
        icon       = "Interface\\Icons\\INV_Drink_06",
    },
    {
        id         = "q_llaves_garganta_fuego_pvp",
        name       = "Las Puertas de Hierro JcJ",
        desc       = "Controla los pasos de montaña clave hacia la Garganta de Fuego exterminando batallones enemigos.",
        minLevel   = 43,
        maxLevel   = 50,
        difficulty = "NORMAL",
        duration   = BotQuestData.DURATIONS.MEDIUM,
        goldMin    = 11000,
        goldMax    = 22000,
        icon       = "Interface\\Icons\\ability_dualwieldspecialization",
        isPvP      = true,
        honorPoints= 700,
    },
    {
        id         = "q_enanos_hierro_negro_garganta",
        name       = "La Fundición de Searing Gorge",
        desc       = "Los enanos Hierro Negro forjan armas oscuras. Sabotea sus fuelles industriales.",
        minLevel   = 44,
        maxLevel   = 50,
        difficulty = "NORMAL",
        duration   = BotQuestData.DURATIONS.MEDIUM,
        goldMin    = 11500,
        goldMax    = 23000,
        icon       = "Interface\\Icons\\Trade_BlackSmithing",
    },
    {
        id         = "q_buhomutados_hinterlands",
        name       = "Los Buhomutantes Salvajes",
        desc       = "Criaturas lunares salvajes de Hinterlands atacan sin razón. Purifica la zona cazándolos.",
        minLevel   = 45,
        maxLevel   = 50,
        difficulty = "NORMAL",
        duration   = BotQuestData.DURATIONS.MEDIUM,
        goldMin    = 12000,
        goldMax    = 24000,
        icon       = "Interface\\Icons\\inv_misc_herb_ancientlichen",
    },
    {
        id         = "q_trols_jintha_alor",
        name       = "El Altar de Jintha'Alor",
        desc       = "Sube a la cúspide de la ciudad trol élite de Hinterlands y destruye los fetiches de sacrificio.",
        minLevel   = 46,
        maxLevel   = 50,
        difficulty = "HARD",
        duration   = BotQuestData.DURATIONS.LONG,
        goldMin    = 14000,
        goldMax    = 28000,
        icon       = "Interface\\Icons\\INV_Misc_Bone_HumanSkull_02",
    },
    {
        id         = "q_ciudaddel_enano_badlands",
        name       = "Las Ruinas de Uldaman",
        desc       = "Registra las afueras de la excavación enana y elimina los troggs mutados por energía titánica.",
        minLevel   = 47,
        maxLevel   = 50,
        difficulty = "HARD",
        duration   = BotQuestData.DURATIONS.LONG,
        goldMin    = 14500,
        goldMax    = 29000,
        icon       = "Interface\\Icons\\INV_Stone_02",
    },
    {
        id         = "q_elementales_un goro",
        name       = "El Cráter de Un'Goro",
        desc       = "Recoge cristales de energía puros custodiados por dinosaurios agresivos e hiladores de fuego.",
        minLevel   = 48,
        maxLevel   = 50,
        difficulty = "HARD",
        duration   = BotQuestData.DURATIONS.LONG,
        goldMin    = 15000,
        goldMax    = 30000,
        icon       = "Interface\\Icons\\INV_Misc_Gem_Stone_01",
    },
    {
        id         = "q_escarabajos_silithus_baja",
        name       = "Exploradores de Silithus",
        desc       = "Los primeros insectos de las colmenas se asoman en los bordes del desierto. Elimínalos ya.",
        minLevel   = 49,
        maxLevel   = 50,
        difficulty = "HARD",
        duration   = BotQuestData.DURATIONS.LONG,
        goldMin    = 16000,
        goldMax    = 32000,
        icon       = "Interface\\Icons\\INV_Misc_Eye_02",
    },
    {
        id         = "q_jefe_tar_un goro",
        name       = "El Guardián del Altar de Alquitrán",
        desc       = "Destruye al elemental de lodo negro masivo que habita en los pozos de alquitrán de Un'Goro.",
        minLevel   = 50,
        maxLevel   = 50,
        difficulty = "ELITE",
        duration   = BotQuestData.DURATIONS.EPIC,
        goldMin    = 20000,
        goldMax    = 40000,
        icon       = "Interface\\Icons\\Spell_Nature_StrangleVines",
    },

    -- ─── NIVEL 51-60 (10 Misiones) ──────────────────────────
    {
        id         = "q_esencia_azul_azshara",
        name       = "El Linaje de Azshara",
        desc       = "Los dragonantes del Vuelo Azul custodian runas en los acantilados. Recupera sus escamas mágicas.",
        minLevel   = 51,
        maxLevel   = 60,
        difficulty = "EASY",
        duration   = BotQuestData.DURATIONS.SHORT,
        goldMin    = 28000,
        goldMax    = 55000,
        icon       = "Interface\\Icons\\INV_Misc_Head_Dragon_Blue",
    },
    {
        id         = "q_fantasmas_stratholme_ext",
        name       = "Las Almas de Stratholme",
        desc       = "Espíritus atormentados vagan por las calles exteriores de la ciudad destruida. Exorcízalos.",
        minLevel   = 52,
        maxLevel   = 60,
        difficulty = "EASY",
        duration   = BotQuestData.DURATIONS.SHORT,
        goldMin    = 29000,
        goldMax    = 58000,
        icon       = "Interface\\Icons\\Spell_Shadow_AnimateDead",
    },
    {
        id         = "q_cultistas_scholomance",
        name       = "Los Acólitos de Caer Darrow",
        desc       = "Cultistas de la Plaga protegen la entrada del fuerte de la isla. Limpia el puente fortificado.",
        minLevel   = 53,
        maxLevel   = 60,
        difficulty = "NORMAL",
        duration   = BotQuestData.DURATIONS.MEDIUM,
        goldMin    = 31000,
        goldMax    = 62000,
        icon       = "Interface\\Icons\\Spell_Shadow_AntiShadow",
    },
    {
        id         = "q_brujos_jaedenar",
        name       = "Las Sombras de Jaedenar",
        desc       = "El Consejo de la Sombra opera en las cuevas oscuras de Felwood. Elimina a sus súcubos e invocadores.",
        minLevel   = 54,
        maxLevel   = 60,
        difficulty = "NORMAL",
        duration   = BotQuestData.DURATIONS.MEDIUM,
        goldMin    = 33000,
        goldMax    = 66000,
        icon       = "Interface\\Icons\\Spell_Shadow_SummonSuccubus",
    },
    {
        id         = "q_trolls_ruinas_eldarath",
        name       = "Los Elfos Noche de Azshara",
        desc       = "Fantasmas altopatricios protegen reliquias sagradas en los templos inundados. Roba sus pergaminos.",
        minLevel   = 55,
        maxLevel   = 60,
        difficulty = "NORMAL",
        duration   = BotQuestData.DURATIONS.MEDIUM,
        goldMin    = 34000,
        goldMax    = 68000,
        icon       = "Interface\\Icons\\INV_Misc_Bone_ElfSkull_01",
    },
    {
        id         = "q_cenarion_silithus_credito",
        name       = "Los Textos Crepusculares",
        desc       = "Asalta los campamentos del Martillo Crepuscular en Silithus para recuperar sus códigos secretos.",
        minLevel   = 56,
        maxLevel   = 60,
        difficulty = "HARD",
        duration   = BotQuestData.DURATIONS.LONG,
        goldMin    = 39000,
        goldMax    = 82000,
        icon       = "Interface\\Icons\\INV_Misc_Book_11",
    },
    {
        id         = "q_torres_peste_oeste_pvp",
        name       = "Torres de Andorhal JcJ",
        desc       = "Las facciones luchan por las ruinas centrales de Tierras de la Peste del Oeste. Captura el centro estratégico.",
        minLevel   = 57,
        maxLevel   = 60,
        difficulty = "HARD",
        duration   = BotQuestData.DURATIONS.LONG,
        goldMin    = 42000,
        goldMax    = 88000,
        icon       = "Interface\\Icons\\INV_BannerPVP_02",
        isPvP      = true,
        honorPoints= 1350,
    },
    {
        id         = "q_elementales_rocanegra_interior",
        name       = "La Forja de la Montaña Roca Negra",
        desc       = "Elementales ígneos colosales patrullan los pasajes interiores de la montaña. Destruye sus esencias.",
        minLevel   = 58,
        maxLevel   = 60,
        difficulty = "HARD",
        duration   = BotQuestData.DURATIONS.LONG,
        goldMin    = 44000,
        goldMax    = 90000,
        icon       = "Interface\\Icons\\Spell_Fire_Volcano",
    },
    {
        id         = "q_quimeras_winterspring",
        name       = "Las Quimeras de Hielo",
        desc       = "Caza a las quimeras ancestrales de Cuna de Invierno para obtener sus alas congeladas impecables.",
        minLevel   = 59,
        maxLevel   = 60,
        difficulty = "HARD",
        duration   = BotQuestData.DURATIONS.LONG,
        goldMin    = 46000,
        goldMax    = 95000,
        icon       = "Interface\\Icons\\Ability_Hunter_Pet_Chimera",
    },
    {
        id         = "q_jefe_baron_stratholme",
        name       = "El Azote del Ladero de Stratholme",
        desc       = "Entra en el bastión de la Plaga y descabeza al Jinete que coordina los envíos de grano infestado.",
        minLevel   = 60,
        maxLevel   = 60,
        difficulty = "ELITE",
        duration   = BotQuestData.DURATIONS.EPIC,
        goldMin    = 60000,
        goldMax    = 120000,
        icon       = "Interface\\Icons\\Spell_Shadow_DeathandDecay",
    },

    -- ─── NIVEL 61-70 (10 Misiones - Outland) ─────────────────
    {
        id         = "q_orcos_viles_peninsula",
        name       = "La Sangre de los Orcos Viles",
        desc       = "Los orcos corruptos de la Ciudadela del Fuego Infernal atacan las rutas. Mitiga su número.",
        minLevel   = 61,
        maxLevel   = 70,
        difficulty = "EASY",
        duration   = BotQuestData.DURATIONS.SHORT,
        goldMin    = 52000,
        goldMax    = 105000,
        icon       = "Interface\\Icons\\INV_Helmet_49",
    },
    {
        id         = "q_bombeo_marisma",
        name       = "Sabotaje en la Bomba de Vapor",
        desc       = "Los naga de la Reserva Colmillo Torcido drenan los lagos. Destruye sus generadores de vapor.",
        minLevel   = 62,
        maxLevel   = 70,
        difficulty = "EASY",
        duration   = BotQuestData.DURATIONS.SHORT,
        goldMin    = 56000,
        goldMax    = 112000,
        icon       = "Interface\\Icons\\Spell_Frost_SummonWaterElemental",
    },
    {
        id         = "q_halconeros_terokkar",
        name       = "Los Jinetes de Terokkar",
        desc       = "Los arakkoa de Skettis mandan espías kaliri a los bosques. Derriba a sus aves mensajeras.",
        minLevel   = 63,
        maxLevel   = 70,
        difficulty = "NORMAL",
        duration   = BotQuestData.DURATIONS.MEDIUM,
        goldMin    = 68000,
        goldMax    = 138000,
        icon       = "Interface\\Icons\\ability_hunter_pet_dragonhawk",
    },
    {
        id         = "q_etereos_nagrand",
        name       = "Los Contrabandistas Etéreos",
        desc       = "Los etéreos del Consorcio están robando fragmentos flotantes en Nagrand. Desmantela sus campamentos.",
        minLevel   = 64,
        maxLevel   = 70,
        difficulty = "NORMAL",
        duration   = BotQuestData.DURATIONS.MEDIUM,
        goldMin    = 72000,
        goldMax    = 145000,
        icon       = "Interface\\Icons\\Spell_Nature_WispSplode",
    },
    {
        id         = "q_halaa_recursos_pvp",
        name       = "El Estandarte de Halaa JcJ",
        desc       = "La ciudad fortificada de Halaa está bajo disputa. Planta tu bandera eliminando defensores contrarios.",
        minLevel   = 65,
        maxLevel   = 70,
        difficulty = "HARD",
        duration   = BotQuestData.DURATIONS.LONG,
        goldMin    = 88000,
        goldMax    = 175000,
        icon       = "Interface\\Icons\\INV_BannerPVP_03",
        isPvP      = true,
        honorPoints= 2100,
    },
    {
        id         = "q_ogros_nagrand_filas",
        name       = "Los Ogros de Vanguardia",
        desc       = "Los ogros de la montaña de Nagrand planean invadir los asentamientos de llanura. Elimina sus brutos.",
        minLevel   = 66,
        maxLevel   = 70,
        difficulty = "NORMAL",
        duration   = BotQuestData.DURATIONS.MEDIUM,
        goldMin    = 76000,
        goldMax    = 155000,
        icon       = "Interface\\Icons\\achievement_dungeon_ulduarraid_misc_06",
    },
    {
        id         = "q_gloria_gromgol",
        name       = "El Trono de Elementos",
        desc       = "Furia de fuego sacude el Valle Sombraluna. Mitiga las manifestaciones viles en las grietas de lava.",
        minLevel   = 67,
        maxLevel   = 70,
        difficulty = "HARD",
        duration   = BotQuestData.DURATIONS.LONG,
        goldMin    = 92000,
        goldMax    = 185000,
        icon       = "Interface\\Icons\\spell_fire_fire",
    },
    {
        id         = "q_cristales_netherstorm",
        name       = "Las Bio-domos de Tormenta Abisal",
        desc       = "Los tecnomagos goblins informan de sabotajes en los ecosistemas cerrados. Repara los domos rúnicos.",
        minLevel   = 68,
        maxLevel   = 70,
        difficulty = "HARD",
        duration   = BotQuestData.DURATIONS.LONG,
        goldMin    = 96000,
        goldMax    = 195000,
        icon       = "Interface\\Icons\\spell_shadow_siphonmana",
    },
    {
        id         = "q_forjas_shadowmoon",
        name       = "Las Forjas de la Legión",
        desc       = "Infiltración en las bases de ingeniería de Illidan para destruir los Mecanostriders viles en producción.",
        minLevel   = 69,
        maxLevel   = 70,
        difficulty = "HARD",
        duration   = BotQuestData.DURATIONS.LONG,
        goldMin    = 105000,
        goldMax    = 210000,
        icon       = "Interface\\Icons\\Spell_Shadow_DeathCoil",
    },
    {
        id         = "q_jefe_kaelthas_muelles",
        name       = "El Comandante de la Furia del Sol",
        desc       = "El lugarteniente de Kael'thas custodia los planos del pozo solar en Quel'Danas. Ejecútalo.",
        minLevel   = 70,
        maxLevel   = 70,
        difficulty = "ELITE",
        duration   = BotQuestData.DURATIONS.EPIC,
        goldMin    = 130000,
        goldMax    = 260000,
        icon       = "Interface\\Icons\\Spell_Holy_MagicalSentry",
    },

    -- ─── NIVEL 71-80 (10 Misiones - Northrend) ───────────────
    {
        id         = "q_vrykuls_borean",
        name       = "Los Vrykul de Utgarde",
        desc       = "Los gigantes nórdicos de la costa asaltan los barcos de suministros. Detén sus drakkares.",
        minLevel   = 71,
        maxLevel   = 80,
        difficulty = "EASY",
        duration   = BotQuestData.DURATIONS.SHORT,
        goldMin    = 155000,
        goldMax    = 310000,
        icon       = "Interface\\Icons\\INV_Helmet_74",
    },
    {
        id         = "q_malygos_nex_baja",
        name       = "Líneas Ley de Coldarra",
        desc       = "El Vuelo Azul altera los conductos mágicos del mundo. Estabiliza las fallas de energía.",
        minLevel   = 72,
        maxLevel   = 80,
        difficulty = "EASY",
        duration   = BotQuestData.DURATIONS.SHORT,
        goldMin    = 165000,
        goldMax    = 330000,
        icon       = "Interface\\Icons\\Spell_Nature_WispSplode",
    },
    {
        id         = "q_furia_fauces",
        name       = "Conflictos en Colinas Pardas",
        desc       = "Las escaramuzas entre tramperos locales y licántropos Fauces de Madera amenazan los campamentos.",
        minLevel   = 73,
        maxLevel   = 80,
        difficulty = "NORMAL",
        duration   = BotQuestData.DURATIONS.MEDIUM,
        goldMin    = 185000,
        goldMax    = 390000,
        icon       = "Interface\\Icons\\Ability_Druid_KIngOfTheJungle",
    },
    {
        id         = "q_trols_draktharon",
        name       = "La Plaga de Gundrak",
        desc       = "Los trols Drakkari sacrifican a sus propios Dioses Salvajes debido a la desesperación. Intercepta los altares.",
        minLevel   = 74,
        maxLevel   = 80,
        difficulty = "NORMAL",
        duration   = BotQuestData.DURATIONS.MEDIUM,
        goldMin    = 195000,
        goldMax    = 410000,
        icon       = "Interface\\Icons\\INV_Misc_Bone_06",
    },
    {
        id         = "q_conquista_invierno_torres_pvp",
        name       = "Talleres de Conquista JcJ",
        desc       = "Captura las fábricas de vehículos del sur en los campos de batalla helados para asegurar el asedio.",
        minLevel   = 75,
        maxLevel   = 80,
        difficulty = "HARD",
        duration   = BotQuestData.DURATIONS.LONG,
        goldMin    = 260000,
        goldMax    = 520000,
        icon       = "Interface\\Icons\\inv_gizmo_thebiggerone",
        isPvP      = true,
        honorPoints= 2800,
    },
    {
        id         = "q_culto_malditos_sholazar",
        name       = "Infiltración en la Cuenca de Sholazar",
        desc       = "El Culto de los Malditos sabotea los pilares de los Titanes que protegen el clima tropical de la cuenca.",
        minLevel   = 76,
        maxLevel   = 80,
        difficulty = "NORMAL",
        duration   = BotQuestData.DURATIONS.MEDIUM,
        goldMin    = 210000,
        goldMax    = 430000,
        icon       = "Interface\\Icons\\achievement_zone_stranglethorn_01",
    },
    {
        id         = "q_hierro_negro_stormpeaks",
        name       = "Los Enanos Mecánicos de Thorim",
        desc       = "Estructuras rúnicas creadas por Loken marchan por las cumbres níveas. Destruye sus circuitos.",
        minLevel   = 77,
        maxLevel   = 80,
        difficulty = "HARD",
        duration   = BotQuestData.DURATIONS.LONG,
        goldMin    = 280000,
        goldMax    = 580000,
        icon       = "Interface\\Icons\\INV_Misc_Gear_02",
    },
    {
        id         = "q_vanguardia_argent_icecrown",
        name       = "El Frente del Veredicto",
        desc       = "Establece cabezas de playa en los riscos de Corona de Hielo usando cañones de asedio de la Cruzada.",
        minLevel   = 78,
        maxLevel   = 80,
        difficulty = "HARD",
        duration   = BotQuestData.DURATIONS.LONG,
        goldMin    = 320000,
        goldMax    = 640000,
        icon       = "Interface\\Icons\\Spell_Holy_BlessingOfStrength",
    },
    {
        id         = "q_protodracos_utgarde",
        name       = "Nidos de Protodracos",
        desc       = "Robar los huevos de los jinetes vrykul en los pináculos de la montaña para debilitar su fuerza aérea.",
        minLevel   = 79,
        maxLevel   = 80,
        difficulty = "HARD",
        duration   = BotQuestData.DURATIONS.LONG,
        goldMin    = 350000,
        goldMax    = 700000,
        icon       = "Interface\\Icons\\INV_Misc_Head_Dragon_01",
    },
    {
        id         = "q_jefe_anubarak_cripta",
        name       = "El Rey Traidor de Azjol-Nerub",
        desc       = "Viaja a las profundidades del reino subterráneo y ejecuta al antiguo monarca nerubiano alzado por la Plaga.",
        minLevel   = 80,
        maxLevel   = nil,
        difficulty = "ELITE",
        duration   = BotQuestData.DURATIONS.EPIC,
        goldMin    = 550000,
        goldMax    = 1100000,
        icon       = "Interface\\Icons\\INV_Misc_MonsterSpiderCarapace_01",
    },
-- ─── ÉLITE 53-60 ─────────────────────────────────────────
    {
        id         = "q_elite_puertas_plaga_avalon",
        name       = "[ÉLITE] Las Puertas de la Plaga: Avalón Occidental",
        desc       = "La Plaga avanza sin descanso por el Frente Occidental. Tu escuadrón debe contener una oleada de no-muertos mientras el último sacerdote sella el portal de invocación. Cada segundo cuenta. No hay retirada.",
        minLevel   = 53,
        maxLevel   = 60,
        difficulty = "ELITE",
        duration   = 3300,
        goldMin    = 130000,
        goldMax    = 260000,
        icon       = "Interface\\Icons\\Spell_Shadow_DeathAndDecay",
    },
    {
        id         = "q_elite_pacto_roto_scholomance",
        name       = "[ÉLITE] El Pacto Roto de Scholomance",
        desc       = "Un archimago renegado ha tomado el control de Scholomance rompiendo el pacto con la Kirin Tor. Sus experimentos amenazan con liberar una plaga mágica. Penetra sus defensas, destruye sus notas y elimínalo.",
        minLevel   = 53,
        maxLevel   = 60,
        difficulty = "ELITE",
        duration   = 3600,
        goldMin    = 140000,
        goldMax    = 280000,
        icon       = "Interface\\Icons\\Spell_Arcane_PortalDalaran",
    },

    {
        id         = "ELITE_01",
        name       = "[ÉLITE] El Azote de Stratholme",
        desc       = "Envía a tus mejores hombres a limpiar los remanentes de la Plaga. La resistencia es feroz y requerirá una coordinación perfecta.",
        minLevel   = 55,
        maxLevel   = 60,
        difficulty = "ELITE",
        duration   = 1800,
        goldMin    = 150000,
        goldMax    = 300000,
        icon       = "Interface\\Icons\\Spell_Shadow_AnimateDead",
    },
    {
        id         = "ELITE_02",
        name       = "[ÉLITE] Núcleo de Magma: Incursión",
        desc       = "Los señores de fuego amenazan con despertar. Solo un grupo con equipamiento excepcional saldrá con vida.",
        minLevel   = 60,
        maxLevel   = 80,
        difficulty = "ELITE",
        duration   = 3600,
        goldMin    = 500000,
        goldMax    = 1000000,
        icon       = "Interface\\Icons\\spell_nature_shamanrage",
    },
    {
        id         = "ELITE_03",
        name       = "[DESAFÍO] Asalto a la Ciudadela",
        desc       = "Una misión suicida a las puertas del Trono helado. El escalado de poder requerido es absurdo.",
        minLevel   = 80,
        maxLevel   = 80,
        difficulty = "ELITE",
        duration   = 5400,
        goldMin    = 2000000,
        goldMax    = 5000000,
        icon       = "Interface\\Icons\\Achievement_Boss_LichKing",
    },
}

-- ============================================================
--  Filtrar misiones por nivel del jugador
-- ============================================================
function BotQuestData:GetQuestsForLevel(level)
    local result = {}
    for _, quest in ipairs(self.QUESTS) do
        local minOk = level >= quest.minLevel
        local maxOk = (quest.maxLevel == nil) or (level <= quest.maxLevel)
        if minOk and maxOk then
            result[#result + 1] = quest
        end
    end
    return result
end

-- Formato legible de duración
function BotQuestData:FormatDuration(seconds)
    if seconds < 60 then
        return seconds .. "s"
    elseif seconds < 3600 then
        return math.floor(seconds / 60) .. " min"
    else
        return math.floor(seconds / 3600) .. "h " .. math.floor((seconds % 3600) / 60) .. "min"
    end
end

-- Formato legible de oro
function BotQuestData:FormatGold(copper)
    local gold   = math.floor(copper / 10000)
    local silver = math.floor((copper % 10000) / 100)
    local cop    = copper % 100
    local str = ""
    if gold   > 0 then str = str .. "|cffffd700" .. gold   .. "o|r " end
    if silver > 0 then str = str .. "|cffc0c0c0" .. silver .. "p|r " end
    if cop    > 0 then str = str .. "|cffb87333" .. cop    .. "c|r" end
    return str ~= "" and str or "0c"
end
